ALTER TABLE `picklog` 
ADD `cardval0` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval1` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval2` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval3` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0';
