ALTER TABLE `inventory` 
ADD `cardval0` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval1` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval2` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval3` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `cart_inventory` 
ADD `cardval0` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval1` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval2` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval3` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `storage` 
ADD `cardval0` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval1` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval2` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval3` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `guild_storage` 
ADD `cardval0` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval1` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval2` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval3` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `mail` 
ADD `cardval0` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval1` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval2` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval3` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `auction` 
ADD `cardval0` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval1` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval2` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
ADD `cardval3` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0';
